### ISSUE TITLE
Skip authentication on LAN?

### ISSUE THREAD

**Issue by BjornB2** [atauenis/webone#122]
Hi!

Is it possible to skip the authentication when the client is on the same LAN as the WebOne server but ask for credentials when the client connects from external location?

Thanks!
Björn

**Comment by atauenis** [comment]
Yes, it's possible to implement such feature, and is not very difficult. I think it should be disabled by default ([that's why](https://stackoverflow.com/questions/7232287/check-if-ip-is-in-lan-behind-firewalls-and-routers#comment8710449_7232612)), but it's a good idea at least for NAT environments with port forwarding.
