### ISSUE TITLE
403 errors trying to hit archive.org

### ISSUE THREAD

**Issue by evert** [atauenis/webone#133]
What a great project! Doesn't just let me browse https sites from Win98, but also seems to speed everything up quite a bit.

When hitting URLs from archive.org, like : https://archive.org/details/softwarelibrary_msdos_games I get 403 errors.

Probably not a webone problem (maybe webone is detected as a bot?), but I just wanted to see if this is a known issue.

Cheers,
Evert

**Comment by atauenis** [comment]
This is caused by update of Archive.org. It detecting old browser, and attempting to redirect to some lite version of page (http://archive.org/details/softwarelibrary_msdos_games?noscript=true here). However, it's not exists on server, and produces a 404 error.

(Huh, interesting that it's doing via a bit incorrect HTML code:
```HTML
<noscript><div class="no-js-redirect-container" data-owner="nginx"><h2>Redirecting you to a lite version of archive.org...</h2></div><meta http-equiv="refresh" data-owner="nginx" content="0; url=/details/softwarelibrary_msdos_games?noscript=true"></noscript><script src="/offshoot_assets/js/webpack-runtime.135df76a17c60cd34dfc.js">
```
:) )

Then there is a minor bug in WebOne (I will fix it in v0.17.1). It tries to find an archived copy of the page (haha, looks for an archive of archive, ok), which obviously results in a 403 error, and it's displayed as `Unsuccessful Web Archive request: FORBIDDEN.`
