### ISSUE TITLE
Mac OS install guide

### ISSUE THREAD

**Issue by khawkins98** [atauenis/webone#24]
Hi there, thanks for this tool, it's really helpful.

I saw there was no dedicate Mac guide so I added this one: https://github.com/atauenis/webone/wiki/MacOS-X-installation

I figured it would make some kind of PR, but it seems to be live already in a Wikipedia fashion. 

Hope it all checks out and is wanted :)

**Comment by atauenis** [comment]
Thank you! It is great that there is a macOS install guide now. 

I haven't written the article self because the latest macOS version that can I run is 10.8, which is too old for .NET Core apps. Newer versions (10.13+) are not supported by VirtualBox and my real test hardware. 

Have you tried `WebOne` binary file (not `WebOne.dll`)? Theoretically it is a shortcut to `dotnet ./WebOne.dll`, and its analog on Linux is working fine.

**Comment by khawkins98** [comment]
I tried running `WebOne` at first but no matter how I tried I always go some sort of error:

```bash
mac-stratcom12:~ khawkins$ dotnet /Users/username/Downloads/WebOne.0.10.5.osx-x64/WebOne 
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-/Users/khawkins/Downloads/WebOne.0.10.5.osx-x64/WebOne does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

I'm not really familiar with dotnet, so I gave up pretty fast on it and just used the dll.

**Comment by atauenis** [comment]
No, it should run without `dotnet` command, simply:
```
mac-stratcom12:~ khawkins$ /Users/username/Downloads/WebOne.0.10.5.osx-x64/WebOne
```

**Comment by khawkins98** [comment]
Ah, just needed a 

- `chmod +x WebOne`  and then
- `./WebOne`

I'll update that Wiki entry in a bit
