### ISSUE TITLE
Wikipedia bugs in Opera 8.54 and Netscape 4.80

### ISSUE THREAD

**Issue by EgorKuzevanov** [atauenis/webone#33]
Why, after applying the following patch in the webone.conf file, the Opera 8.54 and Netscape 4.80 browsers stop opening Wikipedia ([Russian](http://ru.wikipedia.org) and [English](http://en.wikipedia.org))?:
```
; murder JS & CSS files
[Edit:http://[a-z]*.wiki[a-z]*.[a-z]*/w/load.php]
AddRedirect=about:blank

; murder inline CSS
[Edit:http://[a-z]*.wiki[a-z]*.[a-z]*/]
AddFind=<style data-mw-deduplicate=[a-zA-Z0-9=":\.;\-\+ {}()#,%@/_>]*</style>
AddReplace=<!--Wikipedia CSS removed-->
```
In Opera 8.54, the page loads endlessly. And in Netscape 4.80, when I open Wikipedia, I am redirected to the about:blank page.

**Comment by atauenis** [comment]
This is caused by (again) edit set which I gave to you in #31. They are again incorrect.

For future: for talks about site edits (and fighting against browsers bugs/dumbness) there are special place here: https://github.com/atauenis/webone/discussions . The GitHub Issue section is mostly for reports about the WebOne bugs and feature requests.
