### ISSUE TITLE
Javascript errors on netscape accessing google.com

### ISSUE THREAD

**Issue by ssshake** [atauenis/webone#36]
Hello there, my issue has two purposes. 

1) is to report this issue and get help. 

2) Is to introduce myself because I couldn't find out how to contact you otherwise.

Regarding the issue when I go to google through your proxy on netscape 4 I get these javascript parsing errors just like if I went to google directly. 

![image](https://user-images.githubusercontent.com/1675868/114599382-05eb4e80-9c61-11eb-9f73-62310e0a0c58.png)

I saw mention of your service transpiling JS for older system. If this is true is there something I have to turn on to do this transpiling? Alternatively is there a way I can strip out the javascript?

As for the introduction. My name is Richard Bettridge and I created theoldnet.com two years ago. I have similar goals in mind as you. I want to be able to access various internet resources on my collection of vintage computers.

Over the past year or so I have been speaking to other people who also have this goal in mind. There people have been creating their own tools and services. 

I would like us all to know each other, and to help each other in some form or another. We are all working on very similar stuff, I think it's perhaps wasteful for us to work on each piece in isolation. 

I am really excited about what you are doing here, some of the features are really cool. I want to know more, I want to use your service and I want to help where I can. 

If you have any interest in speaking to me and the group please let me know how best to contact you!

**Comment by atauenis** [comment]
Hello. Your project is looking interesting. Looks like an time machine. But Kaspersky Anti-Virus is blocking some pages on it, saying that "the site can steal data". May be because it is a proxy. :)

About the JavaScript adaptions. WebOne can edit scripts, but only when have find&replace masks. Just like download a page, edit in in Notepad/GEdit/Kate/etc and then open edited file in your browser. Every site requires custom patches (edit sets), it is not possible to make edit sets which will fix all stuff on all sites. Currently default webone.conf is containing only some common CSS fixes and one example JS fix (for http://old-dos.ru website). I have not tried to write edit set for Google.com as this needs a large time and because Netscape have no "Developer tools" like in new browsers, so I can't quickly find all "errors".
